- CHANGELOG.md
- seacatauth/tenant/handler.py
- seacatauth/tenant/providers/mongodb.py
- seacatauth/tenant/service.py
Assign a single tenant to credentials using `POST /tenant_assign/{credentials_id}/{tenant}`.
Unassign a single tenant from credentials using `DELETE /tenant_assign/{credentials_id}/{tenant}`.
The old **set tenants** method has been refactored to use the new assign and unassign methods.
Fixes a bug where tenants can be assigned only by superuser. 
Now they can be assigned also by **tenant admin**.
> Simple tenant un/assignment

- CHANGELOG.md
- seacatauth/authz/resource/handler.py
- seacatauth/authz/role/handler/role.py
- seacatauth/authz/role/service.py
- seacatauth/tenant/handler.py
Default limits for `GET /role` and `GET /resource` are now set to `None` so it will fetch the whole list.
Also fixed critical typo in tenant creation method.
> Remove default list limits for roles and resources

- CHANGELOG.md
- doc/credentials-policy.md
- seacatauth/credentials/handler.py
- seacatauth/credentials/policy.py
Removes `authz:credentials:admin` resource.
Credentials can be created by users with `authz:tenant:admin`.
Credentials can be updated/suspended only by users with `authz:superuser`.
> Remove authz:credentials:admin resource

- CHANGELOG.md
- seacatauth/authz/rbac/service.py
- seacatauth/authz/role/handler/role.py
- seacatauth/authz/role/handler/roles.py
- seacatauth/authz/role/service.py
Introducing two new endpoints for un/assigning a single role (as an alternative to the bulk **set roles** call):
- `POST /role_assign/{credentials_id}/{role_id}` assigns a role to credentials.
- `DELETE /role_assign/{credentials_id}/{role_id}` unassigns a role from credentials.
> Simple un/assign role methods

- CHANGELOG.md
- seacatauth/cookie/service.py
- seacatauth/session/service.py
Root cookie domain is now inferred from Auth WebUI base URL.
Missing session AES key now logs a message with config instructions.
> Set reasonable config defaults

- CHANGELOG.md
- seacatauth/authz/resource/handler.py
- seacatauth/authz/resource/service.py
Add `description` property to resource objects.
**`BREAKING`** The **Create resource** call is now `POST` instead of `PUT`, i.e. `POST /resource/{resource_id}`.
It CAN have an optional JSON body containing the `description` property.
Added **Update resource description** endpoint:
```json
PUT /resource/{resource_id}
{
"description": "<resource_description_here>"
}
```
> Resource description

- CHANGELOG.md
- seacatauth/authn/m2m.py
- seacatauth/cookie/handler.py
- seacatauth/generic.py
- seacatauth/middleware.py
- seacatauth/openidconnect/handler/introspect.py
- seacatauth/openidconnect/handler/session.py
- seacatauth/openidconnect/service.py
- seacatauth/session/builders.py
All introspection endpoints can now perform resource checks. To do so, add `resource=<REQUIRED_RESOURCE>` as query parameter. Multiple such parameters can be added (e.g. `resource=my-app:access&resource=my-app:admin`). The check must pass on all the resources in order to result in 200.
**`BREAKING`** Checking tenant access with `verify=tenant` and `X-Tenant` header has been disabled.
Nginx introspection endpoint examples:
```nginx
location = /_cookie_introspect {
internal;
proxy_method          POST;
proxy_set_body        "$http_authorization";
proxy_pass            http://seacatauth:8081/seacat_auth/api/cookie/nginx?resource=my-app:access;
proxy_ignore_headers  Cache-Control Expires Set-Cookie;
}
location = /_oauth2_introspect {
internal;
proxy_method          POST;
proxy_set_body …
```
> Enable resource check in introspection

- .gitignore
- seacatauth/app.py
- seacatauth/middleware.py
- seacatauth/openidconnect/service.py
Eventually, I decided for rather "additive" approach. Removing authentication and authorization from private_auth_middleware_factory made these endpoints inaccessible from the frontend.
> Metrics endpoint access

- CHANGELOG.md
- seacatauth/authn/m2m.py
- seacatauth/credentials/policy.py
- seacatauth/credentials/service.py
- Handle nonexisting provider in M2M introspection
- Hardcoded creation policy for M2M provider - only username and password is required for M2M credentials creation
- Editing disabled for M2M credentials
> M2M credentials policy

- CHANGELOG.md
- seacatauth/credentials/handler.py
Rename `PUT /usernames` to `PUT /idents`. Keep the old endpoint for backward compatibility (until UI adapts).
If a user has no username, provide fallback ident (username > email > phone > credentials ID).
> Credentials: Fallback values in ident translation

- CHANGELOG.md
- seacatauth/authz/__init__.py
- seacatauth/authz/resource/handler.py
- seacatauth/authz/resource/service.py
- seacatauth/authz/utils.py
- seacatauth/batman/elk.py
- seacatauth/batman/grafana.py
- seacatauth/session/builders.py
- Batman for ELK uses resources prefixed with `elk:` (configurable) as a proxy for ELK roles.
- Proxying with SCA roles is supported for backwards compatibility, but will soon be removed.
- ELK resources are initialized automatically in SCA.
- `GET /resource` now accepts filter query parameter `f=`
> Batman: Use resources instead of roles

- CHANGELOG.md
- seacatauth/authn/service.py
- seacatauth/batman/elk.py
- seacatauth/batman/grafana.py
- seacatauth/cookie/handler.py
- seacatauth/cookie/service.py
- seacatauth/middleware.py
- seacatauth/openidconnect/handler/authorize.py
- seacatauth/openidconnect/handler/session.py
- seacatauth/openidconnect/handler/userinfo.py
- seacatauth/openidconnect/service.py
- seacatauth/openidconnect/session.py
- seacatauth/session/__init__.py
- seacatauth/session/adapter.py
- seacatauth/session/builders.py
- seacatauth/session/service.py
Successful login creates a `root` session, under which `openidconnnect` sessions are later created on demand.
These child sessions can (and should) have specific scopes.
- created immediately after successful login
- cookie-based
- usage
- required by `/openidconnect/authorize` to create child `openidconnect` sessions
- account management in Seacat Auth Web UI
- cookie-based client apps and nginx cookie introspection (this is likely temporary and will be replaced by dedicated `cookie` sessions)
- created by `/openidconnect/authorize`
- no cookie, only OAuth2 tokens and OIDC data
- always has a `root` session as a parent
- deleting this parent session causes the deletion of this session as well
- usage
- nginx oauth2 introspection
- cookie-based client apps
- created at m2m introspection
- …
> Session types and hierarchy

- CHANGELOG.md
- seacatauth/authn/handler.py
- seacatauth/authn/login_factors/smscode.py
- seacatauth/authn/login_session.py
- seacatauth/authn/service.py
- seacatauth/communication/sms_smsbranacz.py
- Fix storing ident, session expiration and SMS login data in the login session
- Introduce mock mode in SMS provider (SMS messages are not sent but rather printed to log). Configure by `mock=yes`.
> Fix login session data

- CHANGELOG.md
- seacatauth/session/service.py
- The `SessionService.touch(session)` method updates the expiration of `session`'s parent session and all its child sessions.
> Always update the expiration of the whole session group

- CHANGELOG.md
- seacatauth/credentials/providers/mongodb.py
- seacatauth/credentials/schemas.py
- seacatauth/credentials/service.py
- seacatauth/tenant/handler.py
Credentials update endpoint `PUT /credentials/{credentials_id}` accepts custom `data` object, e.g.:
```json
PUT /credentials/mongodb:default:abc123def456
{
"phone": "123456789",
"data": {
"country": "CZ",
"likes_raccoons": true,
"spoons_owned": 6.1e8
}
}
```
Validation schema for the `data` object:
```json
"data": {
"type": "object",
"description": "Custom data",
"patternProperties": {
"^[a-zA-Z][a-zA-Z0-9_-]{0,126}[a-zA-Z0-9]$": {"anyOf": [
{"type": "string"},
{"type": "number"},
{"type": "boolean"},
{"type": "null"}
]}
},
"additionalProperties": false
}
```
> Custom credentials data

- CHANGELOG.md
- seacatauth/cookie/service.py
- seacatauth/middleware.py
- seacatauth/openidconnect/handler/userinfo.py
> Public API authenticates by cookie only if no Authorization header is present

- CHANGELOG.md
- seacatauth/authn/webauthn/service.py
When migrating to a different hostname, saved webauthn credentials (created on old hostname) are not recognized by frontend.
Webauthn credentials are saved with the ID of the relaying party that created them. When logging in, only the credentials that match the current relaying party ID are usable.
> Webauthn: Store relaying party ID

- CHANGELOG.md
- seacatauth/__init__.py
- seacatauth/app.py
- seacatauth/credentials/service.py
- seacatauth/provisioning/service.py
Most provisioning config is only relevant during the initial provisioning session.
If you need to override provisioning defaults, the provisioning config should be supplied in a dedicated JSON file. Service configuration only contains the path to that file, e.g.:
```ini
[seacatauth:provisioning]
provisioning_config_file=./seacatauth-conf/provisioning.json
```
> Provisioning uses JSON config

- CHANGELOG.md
- seacatauth/openidconnect/service.py
- seacatauth/session/adapter.py
- seacatauth/session/builders.py
The `data` field in credentials object is included in userinfo response as `custom`, e.g.:
```json
{
"sub": "mongodb:ext:60eee70d6b47935cf7bacdda",
...,
"custom": {
"member_of_secret_club": true,
"secret_token": "r8xd4zv28erszver"
}
}
```
> Propagate credentials "data" field to userinfo

- seacatauth/openidconnect/client/handler.py
- seacatauth/openidconnect/client/service.py
returns a JSON object with
- `metadata_schema` which contains the JSON schema for client registration/update, 
- `templates` which contains metadata templates for common client types,
for example:
```json
{
"metadata_schema": {
"type": "object",
"required": [
"redirect_uris"
],
"additionalProperties": false,
"properties": {
"redirect_uris": {
"type": "array",
"description": "Array of Redirection URI values used by the Client."
},
...
}
},
"templates": {
"Public web application": {
"application_type": "web",
"token_endpoint_auth_method": "none",
"grant_types": [
"authorization_code"
],
"response_types": [
"code"
]
},
"Public mobile app": {
"application_type": "native",
"token_endpoint_auth_method": "none"
}
}
}
```
> Client features endpoint with templates

- CHANGELOG.md
- seacatauth/credentials/providers/mongodb.py
- seacatauth/credentials/providers/mongodb_custom.py
- seacatauth/credentials/providers/mysql.py
- seacatauth/credentials/providers/xmongodb.py
- seacatauth/credentials/service.py
Example config
```ini
[seacatauth:credentials:xmongodb:ext2]
mongodb_uri=mongodb://localhost:27017
database=test
collection=users
list=
[
{"$$project": {
"_id": true,
"username": true,
"email": true,
"phone": true,
"suspended": true
}}
]
get=
[
{"$$match": {
"_id": {"$$oid": %(_id)s}
}},
{"$$project": {
"_id": true,
"username": true,
"email": true,
"phone": true,
"suspended": true,
"likes": true
}}
]
locate=
[
{"$$match": {
"$$or": [
{
"username": %(ident)s
},
{
"email": %(ident)s
}
]
}},
{"$$project": {
"_id": true,
"username": true,
"email": true,
"phone": true,
"suspended": true
}}
]
```
**`NOTE:`** All `$` in MongoDB queries are doubled in the config file to pass ConfigParser validation. 
**`NOTE:`** Use `{"$$oid": ...}` instead of `ObjectId(...)`.
> Customizable MongoDB credentials provider

- CHANGELOG.md
- seacatauth/provisioning/service.py
Provisioning creates a role called `superuser` (by default) with `authz:superuser` resource. This role is preserved when provisioning is over.
> Keep superuser role after provisioning

- CHANGELOG.md
- seacatauth/authz/resource/handler.py
- seacatauth/authz/resource/service.py
- seacatauth/authz/role/handler/role.py
- seacatauth/authz/role/service.py
Closes #99 
Closes #100 
Introduce endpoints for renaming and deleting resources. 
**Known limitations:** Deleted resources may still be present in existing sessions and ID tokens.
Resource is marked as deleted, but stays in the database. It is also unassigned from all roles.
```
DELETE /resource/<resource_name>
```
Same endpoint as creating a new resource.
```
POST /resource/<resource_name>
{}
```
Resource is actually deleted from the database. It is also unassigned from all roles.
```
DELETE /resource/<resource_name>?hard_delete=true
```
A shorthand for creating a new resource and deleting the old one.
```
PUT /resource/<old_resource_name>
{
"name": "<new_resource_name>"
}
```
Tenant roles + global roles
```
GET /role/<tenant>?resource=<resource_name>
```
All roles (superuser only)
``` …
```
> Resource rename and delete

- CHANGELOG.md
- seacatauth/middleware.py
- seacatauth/openidconnect/handler/session.py
- seacatauth/openidconnect/service.py
- seacatauth/session/adapter.py
- seacatauth/session/service.py
Fixes #114
ID token and userinfo now contain two new fields:
- `sid`: ID of the client session
- `psid`: ID of the parent session
Session object can no longer be constructed from ID token data; it must be always fetched from the database.
> Include session ID and parent session ID in userinfo and ID token

- CHANGELOG.md
- seacatauth/credentials/schemas.py
- seacatauth/credentials/service.py
To unset phone or email, send 
```
PUT /credentials/<credential_id>
{<attribute>: null}
```
**`BREAKING`** Empty string is not an accepted value anymore.
Fixed email/phone validation policy.
> Unset phone or email by updating it with null

- CHANGELOG.md
- seacatauth/openidconnect/handler/authorize.py
- `/openidconnect/authorize` with `cookie` in `scope` is requested
- client session is created without SCI
- `reply_with_successful_response` fails because it involves setting a cookie which does not exist in the session
- remove the set_cookie directive (the cookie has already been set anyway; otherwise the authorize call would have failed right at the start)
-  (to be implemented in #127)
- SCI is added to client sessions with `cookie` in scope
- cookie introspection locates session by the combination of SCI and client_id which should be unique
> Hotfix authorize response when cookie is in scope

- CHANGELOG.md
- seacatauth/client/handler.py
- seacatauth/client/service.py
Client registration form now allows for choosing a custom `client_id` instead of the random string generated by the server. This is requested by including `"preferred_client_id": "<MY-PREFERRED-ID>"` in the `POST /client` request body, e.g.:
```json
POST /client
{
"preferred_client_id": "asab-custom-app-webui",
"application_type": "web",
...
}
```
The regex for `preferred_client_id` value is `^[-_a-zA-Z0-9]{8,64}$`.
This functionality can be disabled in the app configuration as following:
```ini
[seacatauth:client]
_allow_custom_client_id=no
```
OAuth recommends that the client_id be a random string so that it is not easily guessable. Allowing the client to choose their own ID may make the client application more vulnerable. (https://www.oauth.com/oauth2-servers/client-registration/client- …
> Client registration: Allow custom client ID

- CHANGELOG.md
- seacatauth/decorators.py
The `access_control` decorator raises `HTTP 403 Forbidden` when any user tries to access a nonexistent tenant.
> Attempts to access a nonexistent tenant should result in HTTP 403

- CHANGELOG.md
- seacatauth/cookie/handler.py
**`BREAKING`** Cookie introspection for anonymous access is moved to a new endpoint `POST /cookie/nginx/anonymous?cid=mongodb:default:123abc456def789`
> Introspection: Separate endpoint for anonymous sessions

- CHANGELOG.md
- seacatauth/external_login/providers/__init__.py
- seacatauth/external_login/providers/facebook.py
Closes #129 
- Follow these information [Web - Facebook login](https://developers.facebook.com/docs/facebook-login/web)
- Just log in as a developer and register new Facebook App
- Setup `Facebook Login` and fill `Valid OAuth Redirect URIs` with exact Seacat endpoint (see [external login](https://docs.teskalabs.com/seacat-auth/config/external-login)) e. g.:
- https://auth.example.xyz/auth/api/seacat_auth/public/ext-login/facebook
- https://auth.example.xyz/auth/api/seacat_auth/public/ext-login-add/facebook
- Copy `app ID & secret` to config
``` Shell
[seacatauth:facebook]
client_id={App ID}
client_secret={App Secret}
```
> Add facebook login support

- CHANGELOG.md
- seacatauth/credentials/registration/handler.py
- seacatauth/credentials/registration/service.py
- Invitations without `expiration` now fall back to default expiration without error.
- Expiration date `expires_at` is now included in the `GET /registration/<code>` response
> Fix the handling of default registration expiration

- CHANGELOG.md
- seacatauth/authn/service.py
- seacatauth/cookie/handler.py
- seacatauth/cookie/service.py
- seacatauth/openidconnect/service.py
- seacatauth/session/builders.py
Replace current non-standard scope values with the standard defined in https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims
- `email` will replace `userinfo:email`
- `phone` will replace `userinfo:phone`
- `profile` will cover all the other Claims
Instead of `scope=userinfo:*`, please use `scope=email phone profile`.
Scope values prefixed with `userinfo:*` are preserved for backwards compatibility, but will be obsoleted at some point.
> Use OIDC-standard scope values

- CHANGELOG.md
- seacatauth/authn/m2m.py
- seacatauth/authn/service.py
- seacatauth/authz/rbac/service.py
M2M sessions now have `tenant:*` in scope, which authorizes the session for all the assigned tenants.
> Add all assigned tenants to M2M session

- CHANGELOG.md
- seacatauth/authz/resource/handler.py
- seacatauth/authz/resource/service.py
- seacatauth/client/__init__.py
- seacatauth/client/service.py
- seacatauth/openidconnect/handler/authorize.py
- seacatauth/openidconnect/handler/token.py
- seacatauth/openidconnect/pkce.py
- seacatauth/openidconnect/service.py
- seacatauth/openidconnect/utils.py
- seacatauth/session/adapter.py
closes #139
PKCE is always enabled in Seacat Auth; it is not necessary to configure the app.
Both `plain` and `S256` code challenge methods are supported.
To be able to use PKCE with your client:
- Register your client and set its `code_challenge_methods` attribute to `["S256"]` (or `["plain"]` if SHA256 is not implemented on the client server)
- A client is allowed to register only one method at once, i.e. it is not possible to set `{"code_challenge_methods": ["S256", "plain"]}`
The PKCE code challenge works as described in [RFC7636](https://datatracker.ietf.org/doc/html/rfc7636#section-4)
> OAuth 2.0 PKCE challenge (RFC7636)

- .github/workflows/ci.yml
- CHANGELOG.md
- seacatauth/authn/handler.py
- seacatauth/client/service.py
- seacatauth/credentials/providers/abc.py
- seacatauth/credentials/providers/dictionary.py
- seacatauth/credentials/providers/elasticsearch.py
- seacatauth/credentials/providers/htpasswd.py
- seacatauth/credentials/providers/ldap.py
- seacatauth/credentials/providers/mongodb.py
- seacatauth/credentials/providers/mysql.py
- seacatauth/credentials/providers/xmongodb.py
- seacatauth/credentials/service.py
- seacatauth/generic.py
- seacatauth/openidconnect/handler/authorize.py
- Clients can register a custom `login_uri`
- Clients can register a `login_key` object
- Authorize request adds `client_id` to login URL query
- Module `seacatauth.generic` contains two convenience functions for working with urls.
Clients can now register a custom `login_uri`, which will be used instead of the default if the client's authorize request requires the user to log in.
Clients can also register a `login_key`, a dictionary (JSON object) which is used for locating credentials at login. It is passed to the `locate` methods of the Credential providers. The default MongoDB provider does not use a login key, but providers with customizable queries may be configured to use it.
The keys of `login_key` must match `^[a-zA-Z][a-zA-Z0-9_-]{0,126}[a-zA-Z0-9]$` and its values must be one of …
> Custom login URI and custom login key

- CHANGELOG.md
- seacatauth/middleware.py
Treat `/doc` as a part of ASAB API to make it possible for people to READ the swagger docs page easily without authenticating. All requests sent to Seacat Auth API from Swagger page will be rejected, as the API requires proper authn+authz.
Access the docs via the internal address of seacat admin API container (e.g. `http://localhost:8081/doc`) in your browser.
**NOTE:  These locations are for internal dev purposes and should not be exposed to the internet.**
> Consider Swagger docs a part of ASAB API

- CHANGELOG.md
- seacatauth/__init__.py
- seacatauth/authn/handler.py
- seacatauth/authn/service.py
- seacatauth/authz/resource/handler.py
- seacatauth/client/service.py
- seacatauth/credentials/providers/abc.py
- seacatauth/credentials/providers/dictionary.py
- seacatauth/credentials/providers/elasticsearch.py
- seacatauth/credentials/providers/htpasswd.py
- seacatauth/credentials/providers/ldap.py
- seacatauth/credentials/providers/mongodb.py
- seacatauth/credentials/providers/mysql.py
- seacatauth/credentials/providers/xmongodb.py
- seacatauth/credentials/service.py
- Client `login_key` attribute is removed.
- Extra login prologue data can be provided in the login-prologue body's `qs` field as query-encoded parameter string, e.g.
```
PUT /public/login.prologue
```
```json
{
"ident": "sophie",
"qs": "loginDomain=example.sk&comment=this+is+a+random+comment",
**JWK_PARAMETERS
}
```
- Specify allowed login data keys as a whitespace-separated list in the `[seacatauth:authentication] custom_login_parameters`. Other parameters will be ignored at login time.
- NOTE: Seacat Auth UI login page transfers its URL query string into the login.prologue request body.
> Get custom login data from login prologue body

- CHANGELOG.md
- seacatauth/client/handler.py
- seacatauth/client/service.py
- seacatauth/openidconnect/handler/authorize.py
- seacatauth/openidconnect/pkce.py
- **`BREAKING`** Client feature `code_challenge_methods` is replaced by `code_challenge_method`, whose value is a single string with possible values `none` (default), `plain` and `S256`. The default value `none` implies that the client will not use PKCE.
- **`BREAKING`** Client is now required to always use the Code Challenge Method they registered or to not use PKCE at all if they registered `none` as the Code Challenge Method.
- **`BREAKING`** `template` is no longer a Client feature.
- Introduced `authorize_uri` client feature. It is not used yet.
- The default `token_endpoint_auth_method` value is now `none`. (The specs prescribe `client_secret_basic` as a default but it is not supported yet by Seacat Auth.)
> Client features refactoring

- CHANGELOG.md
- seacatauth/authn/service.py
- seacatauth/authn/webauthn/service.py
- seacatauth/authz/resource/service.py
- seacatauth/authz/role/service.py
- seacatauth/client/service.py
- seacatauth/credentials/change_password/service.py
- seacatauth/credentials/providers/m2m_mongodb.py
- seacatauth/credentials/providers/mongodb.py
- seacatauth/events.py
- seacatauth/external_login/service.py
- seacatauth/openidconnect/service.py
- seacatauth/otp/service.py
- seacatauth/session/service.py
- seacatauth/tenant/providers/mongodb.py
fixes (#132)
Depends on https://github.com/TeskaLabs/asab/pull/371
Event types are stored in 'events.py' in `EventTypes` class. The usage is the following:
```python
await upsertor.execute(event_type=EventTypes.RESOURCE_UPDATED)
```
All event types are configurable and can be found in one place.
> Webhook: Event type descriptors

- CHANGELOG.md
- seacatauth/authn/service.py
M2M session now has access to all the M2M credentials' assigned tenants.
> Add tenants to M2M session

- CHANGELOG.md
- seacatauth/external_login/handler.py
- seacatauth/external_login/providers/generic.py
- seacatauth/external_login/providers/github.py
- seacatauth/external_login/service.py
- seacatauth/feature/handler.py
depends on https://github.com/TeskaLabs/seacat-auth-webui/pull/26
- **`BREAKING`** refactored external login error messages
- **`BREAKING`** refactored /public/features response
- store email and ident with new external logins
> External login refactoring

- CHANGELOG.md
- seacatauth/authz/role/handler/role.py
- seacatauth/authz/role/service.py
- seacatauth/tenant/handler.py
closes #179 
- In bulk access revoke call `PUT /tenant_unassign_many`, unassign tenant by specifying `"UNASSIGN-TENANT"` as the tenant value, instead of an empty array. This should be more comprehensive.
- Role list `GET /role/<TENANT>` now has an option to exclude global roles. To use it, add `exclude_global=true` to the query string.
> Bulk-unassign tenants using "UNASSIGN-TENANT"

- .github/workflows/ci.yml
- CHANGELOG.md
- Dockerfile
- Fix dockerfile packages to resolve the following startup error
```
File "/app/seacat-auth/seacatauth/session/service.py", line 16, in <module>
import pymongo
File "/usr/lib/python3.10/site-packages/pymongo/__init__.py", line 89, in <module>
from pymongo.collection import ReturnDocument
File "/usr/lib/python3.10/site-packages/pymongo/collection.py", line 35, in <module>
from bson.raw_bson import RawBSONDocument
File "/usr/lib/python3.10/site-packages/bson/raw_bson.py", line 56, in <module>
from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/lib/python3.10/site-packages/bson/__init__.py)
```
- Remove ASAB version tags since the PEP440 issue in ASAB has been fixed.
> Fix pymongo import error

- CHANGELOG.md
- seacatauth/authz/rbac/service.py
- seacatauth/authz/resource/handler.py
- seacatauth/authz/resource/service.py
- seacatauth/authz/role/handler/role.py
- seacatauth/authz/role/handler/roles.py
- seacatauth/authz/role/service.py
- seacatauth/client/handler.py
- seacatauth/credentials/change_password/handler.py
- seacatauth/credentials/handler.py
- seacatauth/credentials/policy.py
- seacatauth/credentials/registration/handler.py
- seacatauth/exceptions.py
- seacatauth/middleware.py
- seacatauth/session/handler.py
- seacatauth/session/service.py
- seacatauth/tenant/handler.py
- seacatauth/tenant/providers/mongodb.py
- seacatauth/tenant/service.py
- test/test_rbac.py
closes #190 
- Admin API endpoints are now protected by specific resources.
- Seacat Admin built-in resources are not editable anymore.
- Implemented built-in Seacat Admin resources as specified in #190. They are automatically created/update on service startup.
- Resource detail may now include `"editable": false` and/or `"global_only": true`.
**Non-editable** resources are Seacat Admin built-in resources and cannot be modified or deleted (not even by a supersuser).
**Global-only** resources cannot be added to tenant proper roles, only to global roles.
Example:
_Request: `GET /resource/authz:superuser`_
_Response:_
```json
{
"_id": "authz:superuser",
"_v": 22,
"_c": "2021-07-01T07:34:17.899000Z",
"_m": "2023-04-11T10:29:46.376000Z",
"description": "Grants superuser access, including the …
```
> Granular resources

- CHANGELOG.md
- seacatauth/authn/handler.py
- seacatauth/openidconnect/handler/authorize.py
- seacatauth/openidconnect/service.py
#184 introduced a bug in the authorize flow, where a list of tuples is used instead of the expected dict.
> Fix login redirect from authorize

- CHANGELOG.md
- seacatauth/client/service.py
- seacatauth/openidconnect/handler/authorize.py
Use the new client attribute `session_expiration` to configure the initial duration of the client's sessions. The value can be either an integer or a float specifying the duration in seconds, or a time-unit string, such as `4 h` or `5 d`.
**`BREAKING`** Session expiration can no longer be specified in the authorize query.
> Client session expiration

- CHANGELOG.md
- seacatauth/tenant/handler.py
- seacatauth/tenant/service.py
Issue: Assigning global roles using the bulk call caused the tenant `*` to be assigned.
That is now fixed. Also, assertion statements have been added to tenant_assign and tenant_unassign methods to make sure `*` is never assigned.
> Do not assign the tenant "*" in bulk assignment

- CHANGELOG.md
- seacatauth/session/service.py
**Why?**
- we have found out some performance issues about sessions
- first one is about iterating for expired sessions 
- second one si about metric - sum of sessions
**Expired sessions**
- fixed with simple index
estimated_document_count
- metric don't use filter, so we can improve it with `estimated_document_count()` method
> Session performance improvement

- CHANGELOG.md
- seacatauth/authn/handler.py
- seacatauth/authn/service.py
- seacatauth/authz/utils.py
- seacatauth/cookie/service.py
- seacatauth/openidconnect/service.py
- seacatauth/session/builders.py
- Creates impersonated root session and sends back a response with a `Set-Cookie` header. 
- Designed as a REST API endpoint. Unlike the POST endpoint, this one does not do any redirections. The redirection is expected to be done by the caller.
- Impersonating credentials with `authz:superuser` resource is now enabled, but the resource is excluded from the impersonated session.
> Impersonation REST API

- CHANGELOG.md
- seacatauth/session/service.py
If track id cannot be transferred at token/cookie entrypoint, generate a new one instead of returning error. This concerns the impersonation flow, among others.
> Fix track ID transfer

- CHANGELOG.md
- seacatauth/__init__.py
- seacatauth/cookie/service.py
- seacatauth/openidconnect/handler/authorize.py
- seacatauth/session/service.py
the expiration of anonymous session (both root and client subsessions!) can now be overwritten by the `anonymous_expiration` configuration option:
```ini
[seacatauth:session]
anonymous_expiration=8 h
```
> Configurable anonymous session expiration

- CHANGELOG.md
- seacatauth/__init__.py
- seacatauth/session/service.py
fixes #222 
The `SessionService.touch()` method updates session `_m` time even if the session is not modified in other ways. This is to record session activity. This update can happen at most once every one minute (by default). This period is configurable with the `touch_cooldown` option in the `[seacatauth:session]` section.
Example:
```ini
[seacatauth:session]
touch_cooldown=5m
```
> Update modtime of active sessions

- CHANGELOG.md
- seacatauth/authn/service.py
- seacatauth/authn/webauthn/service.py
- seacatauth/credentials/change_password/service.py
- seacatauth/credentials/registration/service.py
- seacatauth/exceptions.py
- seacatauth/openidconnect/service.py
- seacatauth/otp/service.py
- seacatauth/session/handler.py
- seacatauth/session/service.py
- Expired database objects are deleted during `Application.housekeeping!` event ([see ASAB docs on housekeeping](https://asab.readthedocs.io/en/latest/asab/pubsub.html#cmdoption-arg-application-housekeeping)) instead of more frequent periodic scans (to minimize the number of database write operations). This includes:
- Sessions
- Login sessions
- OAuth authorization codes
- Incomplete credential registrations
- Incomplete TOTP registrations
- Webauthn challenges
- Password reset tokens
- Expired sessions are excluded from session list, unless `include_expired=yes` is specified in request query.
> Clear expired objects during housekeeping

- CHANGELOG.md
- seacatauth/__init__.py
- seacatauth/app.py
- seacatauth/otp/service.py
- seacatauth/session/service.py
SessionService now shares AES key with asab.StorageService, even though it uses its own AES encryption mechanism.
**`BREAKING`** Session AES key is read from `[asab:storage]` config section.
> Common AES key

- CHANGELOG.md
- seacatauth/audit/service.py
- seacatauth/credentials/handler.py
- seacatauth/openidconnect/service.py
Issue: The audit log is being searched for last login data every time `build_userinfo` is called.
- **`BREAKING`** Last login info is no longer included in userinfo.
- **`BREAKING`** Last login info is no longer included in credentials detail by default. Add `last_login=yes` to request query to include the info in the result.
- PUBLIC API: To get your last login info, use `GET /public/last_login`.
- ADMIN API: To get any user's last login info, use `GET /last_login/{CREDENTIALS_ID}`.
- Audit index for finding last login data is removed to save memory. (Note: It must be removed manually in existing deployments.)
Seacat Admin UI
- In credentials detail, to get the last login data, call `GET /credentials/{CREDENTIALS_ID}?last_login=yes`.
Seacat Auth UI
- In account detail, to get the last …
> Reduce last login reads

- CHANGELOG.md
- docs/integrations/elk.md
- docs/reference/session.md
- seacatauth/authz/resource/service.py
- seacatauth/session/service.py
- `SessionService.touch()` makes sure that the parent session is at least as long as the current subsession.
- Added session type overview to docs.
> Root session must be as long as its longest subsession

- CHANGELOG.md
- docs/integrations/elk.md
- seacatauth/authn/handler.py
- seacatauth/authn/m2m.py
- seacatauth/batman/handler.py
- seacatauth/cookie/handler.py
- seacatauth/cookie/service.py
- seacatauth/openidconnect/service.py
- seacatauth/openidconnect/session.py
- seacatauth/session/adapter.py
- seacatauth/session/service.py
- **`BREAKING`** Old Batman sessions are invalidated.
- Batman token uses native `asab.storage` encryption instead of `seacatauth.session` encryption. This fixes the cryptography error which appears when doing batman introspection for grafana.
- ELK Batman docs updated.
- Added alternative `POST` endpoint for Batman introspection (for consistency with cookie and access token introspection endpoints)
> Fix Batman token encryption

- CHANGELOG.md
- seacatauth/authn/handler.py
- seacatauth/authn/login_session.py
- seacatauth/authn/service.py
- seacatauth/openidconnect/handler/authorize.py
Expiration removed from login and authorize query params for security reasons. Client attribute `session_expiration` should be used instead.
> Expiration removed from login query params

- etc/seacatauth.conf
- example/docker/nginx-conf/nginx.conf
- example/docker/seacatauth-conf/seacatauth.conf
- example/nginx-config/nginx-anonymous.conf
- example/nginx-config/nginx-http.conf
- example/nginx-config/nginx-multisubdomain.conf
- seacatauth/__init__.py
- Introducing well-known default ports for Seacat Auth web containers. (http://gitlab.teskalabs.int/lmio/lmio-docs/-/merge_requests/83)
- **`BREAKING`** The public **Auth API** web container listens on port **3081** by default.
- **`BREAKING`** The non-public **Admin API** web container listens on port **8900** by default.
- You **don't have to include the `[web]` and `[web:public]` sections** unless you don't want to use the default well-known ports.
- **`BREAKING`** In nginx examples, `seacat_auth` in location paths are replaced with `seacat-auth`. (TeskaLabs/seacat-auth-webui#38 and TeskaLabs/seacat-admin-webui#51)
> Well-known default ports

- CHANGELOG.md
- Dockerfile
- seacatauth/credentials/service.py
- Fixed obsolete coroutine handling.
- Dockerfile upgraded to Alpine 3.18 and Python 3.11.
> Upgrade to Python 3.11

- CHANGELOG.md
- example/docker/nginx-conf/nginx.conf
- seacatauth/openidconnect/__init__.py
- seacatauth/openidconnect/handler/discovery.py
- seacatauth/openidconnect/handler/introspect.py
- seacatauth/openidconnect/handler/public_keys.py
- seacatauth/openidconnect/handler/session.py
- seacatauth/openidconnect/handler/token.py
- seacatauth/openidconnect/handler/userinfo.py
- seacatauth/openidconnect/service.py
- Default OIDC Issuer name set to the value of `PUBLIC_AUTH_API`.
- OIDC/OAuth discovery endpoint available at `<PUBLIC_AUTH_API>/.well-known/openid-configuration`. 
- JWKS (public keys) now also available at `<PUBLIC_AUTH_API>/.well-known/jwks.json`.
- Added token revocation endpoint.
- Removed refresh token endpoint.
- Updated example NGINX config accordingly.
- Returns Authorization server metadata as defined in [RFC8414 (OAuth 2.0 Authorization Server Metadata)](https://www.rfc-editor.org/rfc/rfc8414#section-2) and [OpenID Connect Discovery 1.0](https://openid.net/specs/openid-connect-discovery-1_0.html).
Example response:
```json
{
"issuer": "https://auth.local.loc/seacat-auth/api",
"authorization_endpoint": "https://auth.local.loc/seacat-auth/api/openidconnect/authorize", …
```
> OpenID Connect Discovery

- CHANGELOG.md
- Dockerfile
the latest webauthn still has the pydantic v2 incompatibility issue
https://github.com/duo-labs/py_webauthn/issues/156
> Re-lock webauthn package version

- CHANGELOG.md
- seacatauth/openidconnect/handler/discovery.py
Context: 
According to [OIDP Discovery documentation](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata), the discovery endpoint must also return `id_token_signing_alg_values_supported` field. 
When using for example client library for OIDP authentication (AppAuth) configured so that it use the discovery document, the client library refuses to read the discovery document because current implementation does not follow the OIDP Discovery specification. This PR fixes that.
> Add 'id_token_signing_alg_values_supported' to OIDP discovery endpoint response

- CHANGELOG.md
- seacatauth/communication/builders/email.py
- seacatauth/communication/email_smtp.py
- `sender_email_address` config option renamed to `from`.
- Config section `[seacatauth:communication:email:smtp]` is now updated with the content of section `[smtp]`. 
- **NOTE**: The `[seacatauth:communication:email:smtp]` section must still be included (even if empty) for the SMTP provider to be enabled.
Example config:
```ini
[seacatauth:communication:email:smtp]
[smtp]
from=info@example.com
host=smtp.sendgrid.net
user=apikey
password=abcdef123456
ssl=no
starttls=yes
```
> Unified SMTP config

- CHANGELOG.md
- seacatauth/authn/handler.py
- seacatauth/authn/m2m.py
- seacatauth/authn/service.py
- seacatauth/authz/role/service.py
- seacatauth/communication/service.py
- seacatauth/cookie/handler.py
- seacatauth/cookie/service.py
- seacatauth/credentials/change_password/service.py
- seacatauth/credentials/providers/abc.py
- seacatauth/credentials/providers/htpasswd.py
- seacatauth/credentials/providers/ldap.py
- seacatauth/credentials/providers/mongodb.py
- seacatauth/external_login/handler.py
- seacatauth/openidconnect/handler/authorize.py
- seacatauth/openidconnect/handler/introspect.py
- seacatauth/openidconnect/handler/token.py
- seacatauth/openidconnect/service.py
- seacatauth/session/adapter.py
- seacatauth/session/service.py
- Many warning messages changed to error or notice messages.
- Fixed error in Mongo provider's `locate()` method triggered by special characters in ident.
> Revise logging levels

- CHANGELOG.md
- seacatauth/__init__.py
- seacatauth/app.py
- seacatauth/client/service.py
- seacatauth/generic.py
- seacatauth/openidconnect/handler/authorize.py
- seacatauth/openidconnect/service.py
- seacatauth/provisioning/service.py
- Invalid redirect URI in OAuth Authorize request now results in error response.
- As per [rfc6749#section-4.1.2.1](https://www.rfc-editor.org/rfc/rfc6749#section-4.1.2.1), invalid redirect URI or client ID results in an error response **without redirect**.
- Config section `[seacat_auth]` renamed to `[seacatauth]` to unify with all the other sections.
- Authorize audit messages include access IPs.
- Disable all redirect URI validations by toggling the `_disable_redirect_uri_validation` switch in the `[openidconnect]` section.
> Validate redirect URI in authorize request

- CHANGELOG.md
- seacatauth/tenant/providers/mongodb.py
Command `$set` is not available until MongoDB version 4.2. Use `$addFields` instead.
> Support MongoDB version 3.6

- CHANGELOG.md
- seacatauth/authz/resource/service.py
- seacatauth/credentials/registration/handler.py
- Anyone authorized for `seacat:tenant:assign` can use `POST /public/{tenant}/invite` to invite a user to the specified tenant. This endpoint is included in the public API.
- Resending invitation automatically extends its expiration.
> Public invitation API

- CHANGELOG.md
- seacatauth/tenant/handler.py
- seacatauth/tenant/providers/mongodb.py
- seacatauth/tenant/schemas.py
- seacatauth/tenant/service.py
closes #246 
- Tenants now have an optional `label` attribute, which should contain a human-palatable name of the tenant. This attribute (unlike `tenant_id`) supports Unicode.
- Tenant `label` and `data` can now also be set in the tenant creation request.
> Implement tenant label

- CHANGELOG.md
- seacatauth/credentials/policy.py
- Fix the validation of credentials creation data when `email` or `phone` fields are missing.
> Fix validation when creation_data incomplete

- seacatauth/external_login/providers/facebook.py
- seacatauth/external_login/providers/generic.py
- seacatauth/external_login/providers/github.py
- seacatauth/external_login/providers/google.py
- seacatauth/external_login/providers/mojeid.py
- seacatauth/external_login/providers/office365.py
The discovery URI is currently only for documentation purposes. It is not actively used yet.
> Add openid discovery uris to config defaults

- CHANGELOG.md
- seacatauth/audit/service.py
- seacatauth/events.py
- The `version` parameter in upsertor should have been `None`, not zero.
- Remove upsertor because it can trigger webhook, which is unwanted in audit.
> Don't use upsertor in Audit service

- CHANGELOG.md
- seacatauth/external_login/handler.py
- seacatauth/external_login/providers/facebook.py
- seacatauth/external_login/providers/generic.py
- seacatauth/external_login/providers/github.py
- seacatauth/external_login/providers/google.py
- seacatauth/external_login/providers/mojeid.py
- seacatauth/external_login/providers/office365.py
- seacatauth/external_login/service.py
- Add ID token signature validation for identity providers that support it (Google, Office365 and MojeID).
- Rename config options to match OpenID terminology (backwards compatibility preserved):
- `authorize_uri` -> `authorization_endpoint`
- `access_token_uri` -> `token_endpoint`
- `userinfo_uri` -> `userinfo_endpoint`
> External login JWT validation

- CHANGELOG.md
- seacatauth/authn/webauthn/handler.py
- seacatauth/authn/webauthn/service.py
- Webauthn credentials `user_name` can be email, phone or newly username.
- If the user has neither, respond with 400.
> Fix webauthn username

- CHANGELOG.md
- seacatauth/authn/webauthn/service.py
closes #251 
- Registered WebAuthn devices now have a human-readable name (if they are found in the FIDO Metadata Service).
- Preferred attestation changed to `direct`, to request extra weabuthn registration metadata from browsers.
> FIDO metadata

- CHANGELOG.md
- seacatauth/audit/service.py
- seacatauth/cookie/handler.py
see #303 
To disable auditing the creation of anonymous sessions, use the following config:
```ini
[seacatauth:audit]
log_anonymous_sessions=no
```
Auditing the creation of anonymous sessions is still enabled by default.
> Disable auditing anonymous sessions

- CHANGELOG.md
- docs/config/cookies.md
- docs/integrations/elk.md
- docs/integrations/index.md
- example/docker/nginx-conf/nginx.conf
- example/nginx-config/nginx-anonymous.conf
- example/nginx-config/nginx-http.conf
- example/nginx-config/nginx-multisubdomain.conf
- seacatauth/authn/m2m.py
- seacatauth/batman/handler.py
- seacatauth/cookie/handler.py
- seacatauth/middleware.py
- seacatauth/openidconnect/handler/discovery.py
- seacatauth/openidconnect/handler/introspect.py
- seacatauth/openidconnect/service.py
- NGINX introspection endpoints moved from **public API (port 3081)** to **private API (port 8900)**. This is a **security fix** - Nginx introspection is for internal use only!
- NGINX introspection endpoint paths changed so that all start with `/nginx/introspect` for easier filtering (see below for updated paths).
- Batman NGINX introspection method changed to POST (unification with all the other introspection endpoints).
- The old endpoint paths in public API will be **kept until the next release** to allow for smoother transition of existing deployments.
- Recommended upgrade plan (to prevent network downtime):
- Upgrade Seacat Auth to this version.
- Update the introspection URLs and methods in you nginx configuration.
- Upgrade Seacat Auth to newer versions (if available).
- …
> Move NGINX introspection endpoints to private API

- CHANGELOG.md
- seacatauth/authn/m2m.py
- seacatauth/batman/handler.py
- seacatauth/cookie/handler.py
- seacatauth/openidconnect/handler/introspect.py
this is a post-fix to #301
- NGINX introspection endpoints moved from **public API (port 3081)** to **private API (port 8900)**. This is a **security fix** - Nginx introspection is for internal use only!
- NGINX introspection endpoint paths changed so that all start with `/nginx/introspect` for easier filtering (see below for updated paths).
- Batman NGINX introspection method changed to POST (unification with all the other introspection endpoints).
In your NGINX configuration, simply replace the old paths with the new ones:
OLD endpoint | NEW endpoint |
--- | --- |
POST {PUBLIC_API}/openidconnect/introspect/nginx | POST {PRIVATE_API}/nginx/introspect/openidconnect |
POST {PUBLIC_API}/coookie/nginx | POST {PRIVATE_API}/nginx/introspect/cookie |
POST {PUBLIC_API}/cookie/nginx/anonymous | …
> Move NGINX introspection endpoints to private API (post-fix)

- CHANGELOG.md
- example/nginx-config/nginx-websocket-authorization.conf
- seacatauth/generic.py
- seacatauth/openidconnect/handler/introspect.py
see http://gitlab.teskalabs.int/ateska/webui-microfrontends-poc/-/merge_requests/85
- Nginx OAuth introspection checks the `Sec-WebSocket-Protocol` header for access token if no `Authorization` header is present.
Nginx `proxy_cache_key` should concatenate the `Authorization` and `Sec-WebSocket-Protocol` headers:
```nginx
proxy_cache_key       "$http_authorization $http_sec_websocket_protocol";
```
Full introspection location example:
```nginx
location = /_oauth_introspect {
internal;
proxy_method          POST;
proxy_set_body        "$http_authorization";
proxy_set_header      X-Request-Uri "$scheme://$host$request_uri";
proxy_pass            http://seacat_private_api/nginx/openidconnect/introspect?client_id=some-client;
proxy_ignore_headers  Cache-Control Expires Set-Cookie;
proxy_cache …
```
> Authorization for websocket requests

- CHANGELOG.md
- seacatauth/authn/handler.py
- seacatauth/client/service.py
- seacatauth/openidconnect/handler/authorize.py
- seacatauth/openidconnect/service.py
- seacatauth/openidconnect/utils.py
- OpenID Authorization endpoint should ignore all unknown request parameters.
- Standard OAuth / OpenID parameters are at the least acknowledged and preserved in redirections.
- Client secret parameter does not belong in the authorization request, hence it was removed from the method arguments.
- **`BREAKING`** Dropped support for authorize query params `ldid` and `expiration`.
> Allow all standard OIDC authorize params

- CHANGELOG.md
- seacatauth/authz/role/service.py
- seacatauth/batman/grafana.py
Batman syncs with Grafana every minute and logs failed connection for every user. This results in tens of thousands of error messages daily when Grafana is down.
- Use a single grafana connection session when synchronizing all credentials.
- Synchronize all credentials on housekeeping.
- Synchronize individual users on authorization change (role assigned, role unassigned, role auth updated).
> Reduce grafana sync frequency

- CHANGELOG.md
- seacatauth/authn/login_factors/webauthn.py
Sometimes the login request has no webauthn data although it is expected to have it. This is now handled and evaluated as authentication failure.
> Handle missing webauthn data in login request

- CHANGELOG.md
- seacatauth/authz/resource/service.py
- seacatauth/authz/utils.py
- seacatauth/batman/elk.py
- seacatauth/batman/kibana.py
- seacatauth/batman/service.py
- seacatauth/credentials/service.py
- seacatauth/tenant/handler.py
- seacatauth/tenant/service.py
- Batman for Kibana now also requires `kibana_url`. If this is empty, Kibana space sync is disabled.
- Batman does no longer create Seacat resources from all Kibana roles. However, existing `elk:`-prefixed resources are still mapped to corresponding Kibana roles for backward compatibility.
- Config section`batman:elk` has been renamed to `batman:kibana`. The old config still works as fallback.
- When a new tenant (tenant_id=`my-company`) is created in Seacat Auth, Batman service creates a space in Kibana (space_id=`my-company`) and two Elastic roles with access to that space: 
- `tenant_my-company_read` with read-only privileges,
- `tenant_my-company_all` with read-write privileges.
- Spaces are synced primarily on housekeeping, plus on tenant creation or update. This can be disabled by …
> Synchronize Kibana spaces to Seacat tenants

- CHANGELOG.md
- seacatauth/cookie/service.py
- seacatauth/generic.py
- seacatauth/openidconnect/handler/authorize.py
- seacatauth/openidconnect/service.py
- seacatauth/session/adapter.py
- seacatauth/session/builders.py
Instead of storing the entire login descriptor in the session object, store only its ID and its list of used factors.
> Separate login factors in session object

- CHANGELOG.md
- seacatauth/__init__.py
- seacatauth/app.py
- seacatauth/authn/webauthn/service.py
- seacatauth/communication/service.py
- seacatauth/cookie/handler.py
- seacatauth/cookie/service.py
- seacatauth/credentials/change_password/service.py
- seacatauth/credentials/registration/service.py
- seacatauth/external_login/providers/generic.py
- seacatauth/external_login/service.py
- seacatauth/openidconnect/__init__.py
- seacatauth/openidconnect/handler/authorize.py
- seacatauth/openidconnect/handler/discovery.py
- seacatauth/openidconnect/service.py
- seacatauth/otp/service.py
- seacatauth/provisioning/service.py
- Simplify public URL configuration to just one option: `public_server_url` in the `general` section.
- Public server URL can be also supplied via `PUBLIC_URL` environment variable.
- All necessary public URLs (login page, public API, OpenID Connect API, WebAuthn issuer name ...) are derived from `public_url` in canonical deployments.
- `public_url` defaults to `http://localhost` (but produces a warning on app initialization).
- prefix `${PUBLIC_URL}/api/seacat-auth/`
- endpoint URL example `https://example.com/api/seacat-auth/public/login`
- prefix `${PUBLIC_URL}/api/`
- endpoint URL example `https://example.com/api/openidconnect/authorize`
- URL `${PUBLIC_URL}/auth/`
- Page URL example `https://example.com/auth/#/login`
> Unify public URL config

- CHANGELOG.md
- seacatauth/authn/handler.py
- seacatauth/credentials/change_password/handler.py
- seacatauth/credentials/change_password/service.py
- seacatauth/credentials/handler.py
- seacatauth/exceptions.py
- The suspended status is checked at the beginning of the login process, at login prologue time.
- **`CRITICAL`** Password reset is now disabled for suspended credentials. The check is performed both before the reset token is created and before the password is changed.
> Check suspended credentials before login and password reset

- CHANGELOG.md
- seacatauth/middleware.py
- Well-known endpoints must be accessible without any authentication, even in the private container
- `/.well-known/jwks.json` - JSON Web Key Set (the server's public keys)
- `/.well-known/openid-configuration` - OpenID Connect provider metadata
> Well-known endpoints in the private container are available without auth

- CHANGELOG.md
- docs/access/resources.md
- docs/installation/provisioning.md
- docs/reference/resources.md
- seacatauth/__init__.py
- seacatauth/authz/resource/service.py
- seacatauth/middleware.py
- Users no longer need to have `seacat:access` assigned to be able to access Seacat Admin API. All admin endpoints already have their own specific resource identifiers (sucha as `seacat:credentials:edit`, `seacat:client:access` etc.); there is no need for double protection.
> Deprecate "seacat:access" resource ID

- docs/integrations/grafana.md
- docs/integrations/index.md
- mkdocs.yml
- seacatauth/batman/grafana.py
- Document setting up Grafana with Seacat Auth OAuth.
- Add deprecation warning for Batman for Grafana.
> Grafana OAuth documentation

- CHANGELOG.md
- seacatauth/credentials/handler.py
Replace `_` with `-` in last login endpoint path for uniformity.
> Fix typo in last login path

- CHANGELOG.md
- seacatauth/authn/webauthn/service.py
- Handle connection errors gracefully.
- Supply your own MDS JWT file URL (or local file path) using the `metadata_service_url` option in `seacatauth:webauthn` config section.
- Disable the metadata service by configuring `metadata_service_url` in `seacatauth:webauthn` to `DISABLED`.
> Improve error handling in FIDO MDS

- CHANGELOG.md
- seacatauth/authz/resource/service.py
- seacatauth/batman/elasticsearch.py
- seacatauth/batman/grafana.py
- Tenant membership implicitly grants **read access to tenant indices** that match a pre-configured pattern.
- Separated ElasticSearch and Kibana sync operations - Kibana is optional.
- Tenant membership implicitly grants read access to tenant indices that match the pattern `tenant-{tenant}-*`. For this purpose, an ElasticSearch role `index-{tenant}-read` is created for each Seacat tenant.
- The index name pattern can be configured via `tenant_indices` option in `batman:elasticsearch` config section, e.g.:
```ini
[batman:elasticsearch]
tenant_indices=lmio-{tenant}-*
```
- To access a tenant space in Kibana, the user must have access to `tools:kibana:read` resource (or `tools:kibana:all` for read-write access). For this purpose, Kibana roles `space-{tenant}-read` and `space-{tenant}-all` …
> Revise ElasticSearch index and Kibana space authorization

- CHANGELOG.md
- seacatauth/authn/webauthn/service.py
- FIDO metadata request is made by Task Service to prevent blocking the application.
- Request timeout is lowered to 30 seconds.
> Make FIDO MDS request non-blocking using TaskService

- CHANGELOG.md
- seacatauth/authz/resource/service.py
- b6766f4 in #353 introduced a serious bug, making non-editable resources editable and vice versa
- This fixes the mentioned bug
- Also, resources with non-empty `managed_by` property are flagged as non-editable.
> Fix resource editability

- CHANGELOG.md
- seacatauth/authn/service.py
- seacatauth/authn/webauthn/handler.py
- seacatauth/cookie/service.py
- seacatauth/credentials/schemas.py
- seacatauth/exceptions.py
- seacatauth/external_login/providers/appleid.py
- seacatauth/external_login/providers/facebook.py
- seacatauth/external_login/providers/github.py
- seacatauth/external_login/providers/google.py
- seacatauth/external_login/providers/mojeid.py
- seacatauth/external_login/providers/office365.py
- seacatauth/feature/handler.py
- seacatauth/openidconnect/service.py
- seacatauth/otp/handler.py
- seacatauth/otp/service.py
- seacatauth/session/builders.py
Collection of tweaks and fixes made while migrating Seacat Account Webui (http://gitlab.teskalabs.int/ateska/webui-microfrontends-poc/-/merge_requests/148)
- Move `GET /features` endpoint under `/account` since it won't be used in public API anymore.
- FIDO credential name allows any character (it should be a human-palatable name).
- External login provider `label` contains only the display name of the provider, e.g. "AppleID" instead of "Sign in with AppleID".
- TOTP error responses now have error code 400.
> Account web UI migration tweaks

- .github/workflows/ci.yml
- CHANGELOG.md
- Dockerfile
- seacatauth/client/handler.py
- seacatauth/client/service.py
- Add the option to set oauth client secrets. **They are not used yet** until authentication is implemented on token endpoint.
- Added dependency for `argon2_cffi` library. It is used for hashing client secrets only, but will be used for user passwords soon.
> Client secret management

- CHANGELOG.md
- seacatauth/__init__.py
- seacatauth/client/service.py
closes #306
Client metadata are accessed frequently, but they don't change too often. It makes sense to cache them to lower the number of database requests.
Default cache expiration is 30 seconds, it can be configured using the following option:
```ini
[seacatauth:client]
cache_expiration=5m
```
Expired cache entries are deleted every 10 minutes.
Cache is used only for get-client-detail calls, not for get-client-list.
> Client cache

- CHANGELOG.md
- seacatauth/credentials/handler.py
- seacatauth/credentials/service.py
#348 broke credentials searching with multiple filters. It is not possible to search by username when the credentials are already being filtered by tenant or role.
This provides a fix. 
- **The fix is inefficient and will not scale.** Performance optimization will be required.
- The total credentials count is overestimated, which may break pagination. **UI needs to support listing data without known count.**
> Fix searching credentials with multiple filters

- CHANGELOG.md
- seacatauth/authn/login_factors/smscode.py
- seacatauth/communication/email_smtp.py
- seacatauth/communication/service.py
- seacatauth/communication/sms_smsbranacz.py
- seacatauth/credentials/change_password/handler.py
- seacatauth/credentials/change_password/service.py
- seacatauth/credentials/handler.py
- seacatauth/credentials/registration/handler.py
- seacatauth/credentials/registration/service.py
- seacatauth/credentials/service.py
- seacatauth/exceptions.py
- When no communication channel is configured, invitation and password reset URLs are returned in **admin** responses.
- When an invitation request is created for an email that already exists, the invitation message is resent.
- When an invitation request is created for an email of a user that is already registered, that user is simply added to the tenant.
- CommunicationService raises exceptions instead of returning `None`.
- Resending an invitation is now part of `seacat:tenant:assign` resource to keep consistency. It was ~`seacat:tenant:invite`~.
> Invitation URL in response, resending invitations

- .github/workflows/ci.yml
- CHANGELOG.md
- Dockerfile
- seacatauth/client/service.py
- seacatauth/communication/sms_smsbranacz.py
- seacatauth/credentials/providers/abc.py
- seacatauth/credentials/providers/dictionary.py
- seacatauth/credentials/providers/htpasswd.py
- seacatauth/credentials/providers/m2m_mongodb.py
- seacatauth/credentials/providers/mongodb.py
- seacatauth/credentials/providers/mysql.py
- seacatauth/credentials/providers/xmongodb.py
- seacatauth/generic.py
- seacatauth/provisioning/service.py
- Passlib is no longer maintained plus lately it started throwing warnings when used with bcrypt backend (see https://github.com/pyca/bcrypt/issues/684).
- Passlib removed from Dockerfile.
- `passlib.hash.bcrypt` replaced by `bcypt` directly.
- `passlib.hash.argon2` replaced by `argon2` directly.
- `passlib.pwd` replaced by `secrets`.
- `passlib.hash.md5` replaced by `hashlib.md5`.
- `passlib.apache` replaced by custom htpasswd file reader.
- Created utility methods for password hashing and validation in `seacatauth.generic`.
- Method `_verify_password` added to CredentialsProviderABC so that it can be used by any credential provider.
- Default provisioning tenant name must not contain `-`.
> Deprecate passlib

- CHANGELOG.md
- seacatauth/authz/resource/service.py
- seacatauth/authz/role/service.py
- seacatauth/credentials/service.py
- seacatauth/decorators.py
- seacatauth/exceptions.py
- seacatauth/tenant/providers/mongodb.py
- seacatauth/tenant/service.py
- CredentialsService, TenantService, RoleService and ResourceService all raise their dedicated `xxxNotFoundError`s (which inherit from KeyError).
- Resources `seacat:credentials:access` and `seacat:credentials:edit` are not considered global-only.
- Non-superusers cannot edit credentials outside their tenant.
> Consistent use of item-specific not-found exceptions

- CHANGELOG.md
- seacatauth/last_activity/service.py
- seacatauth/openidconnect/handler/authorize.py
- seacatauth/openidconnect/service.py
- On successful authorization request, the authorized tenant is remembered for every credentials.
- When authorization request is made with `tenant` in scope, the last authorized tenant is used.
> Authorize into last active tenant

- CHANGELOG.md
- seacatauth/credentials/change_password/handler.py
When an incorrect old password is entered in the Change password form, authentication failure is logged, but the password change still proceeds. This is a serious security bug.
The server responds with 401 immediately after the failed old password verification. 
This should be considered a hotfix - a proper refactoring is needed:
- ChangePasswordHandler should not perform any verification or flow control.
- ChangePasswordService needs to conduct the entire password change process, including sending the messages etc.
- ChangePasswordService needs to have a specific Error class for every unhappy flow. The Handler must catch those and translate them into HTTP responses.
- Unit tests must be created for all ChangePasswordService methods.
> Deny password change when old password verification fails

- CHANGELOG.md
- seacatauth/credentials/providers/m2m_mongodb.py
- seacatauth/credentials/providers/mongodb.py
- seacatauth/credentials/providers/mysql.py
closes #340 
- New passwords are hashed using Argon2, which is more secure than Bcrypt.
- Bcrypt is still supported for existing passwords.
> Hash passwords using argon2 instead of bcrypt

- CHANGELOG.md
- seacatauth/authn/service.py
Fake login session results in traceback because of AttributeError.
Fix incorrect reference.
> Fix AttributeError in failed login

- CHANGELOG.md
- seacatauth/__init__.py
- seacatauth/credentials/change_password/handler.py
- seacatauth/credentials/change_password/service.py
- seacatauth/exceptions.py
Introducing configurable minimum requirements for user passwords.
This is the default config:
```ini
[seacatauth:password]
min_length=10
max_length=64
min_lowercase_count=1
min_uppercase_count=1
min_digit_count=1
min_special_count=1
```
The requirements are available at `GET /public/password/policy` and `GET /account/password/policy`. Example response:
```json
{
"min_length": 10,
"min_lowercase_count": 1,
"min_uppercase_count": 1,
"min_digit_count": 1,
"min_special_count": 1
}
```
This endpoint should be used by the UI to give the user relevant hints on password strength.
Dynamic password requirements are supported by
- [Seacat Auth Webui v24.19-alpha](https://github.com/TeskaLabs/seacat-auth-webui/releases/tag/v24.19-alpha) and later
- [Seacat Account Webui …
> Configurable basic password requirements

- CHANGELOG.md
- seacatauth/generic.py
#375 and #359 introduced a bug in password verification: Incorrect password triggers a stacktrace.
Handle the raised error and return False where it is expected.
> Properly handle Argon2 VerifyMismatchError

- CHANGELOG.md
- seacatauth/credentials/providers/ldap.py
When LDAP user tries to log in with incorrect password, it is logged as ERROR. The log level should be lower since it is not an application failure.
Log level decreased to NOTICE.
> Do not log failed LDAP login as error

- CHANGELOG.md
- seacatauth/cookie/handler.py
- seacatauth/cookie/service.py
- seacatauth/openidconnect/handler/authorize.py
- seacatauth/session/service.py
#358 introduced a bug where client cookie sessions are created with short expiration, which is not extended later and the session expires in a few minutes, logging the user out.
The session was supposed to be extended at the cookie entrypoint, when the auth code is exchanged for a cookie (same as with OAuth token request), but there seems to be no code doing so.
> Extend session expiration on cookie request

- CHANGELOG.md
- seacatauth/cookie/handler.py
- seacatauth/cookie/service.py
When the client cookie introspection fails, the user is logged out completely because their SSO (root) cookie is deleted. When I log into one app and then navigate to another one that uses cookie introspection, my SSO cookie is deleted and I'm required to log in again.
Delete the client cookie instead of the SSO cookie so that a new cookie can be obtained via the authorization code flow without login if needed.
> Delete client cookie on introspection failure

- CHANGELOG.md
- seacatauth/authn/service.py
- seacatauth/session/service.py
fix and re-merge of #387 
Move SSO session creation into session service and refactor for reusability.
> Refactor SSO session creation

- CHANGELOG.md
- seacatauth/generic.py
- seacatauth/openidconnect/handler/authorize.py
- seacatauth/openidconnect/service.py
The function `generic.add_params_to_url_query` parses URLs with query incorrectly with list values, resulting e.g. in `http://localhost:8080/login?param=['test']` instead of `http://localhost:8080/login?param=test`.
- Query parameter values are parsed as strings.
- No parameter can occur in the query more than once (e.g. `?someparam=value1&someparam=value2` is not allowed).
> Properly parse URL query before adding new parameters

- CHANGELOG.md
- seacatauth/session/service.py
Successful re-login leads to logout. This is caused by session cookie value being stored improperly in the DB. This happens only in root SSO session update, i.e. re-login.
Cookie value must be encrypted in session update the same way it is done in session creation.
> Encrypt cookie value in session update

- CHANGELOG.md
- seacatauth/openidconnect/service.py
Sending a non-base64 access token in Authorization header triggers an unhandled error.
Catch the error and log the corrupt access token.
Also fixed for authorization codes and refresh tokens.
> Catch token decoding errors when finding sessions

- CHANGELOG.md
- seacatauth/credentials/service.py
**Updating credentials does not work since #371 (`v24.17-alpha5`)**
Updating credentials causes the following error:
```
26-Jun-2024 12:28:52.929632 ERROR asab.web [sd uuid="615d4178-f178-4012-88a3-724f249001b0" path="/account/credentials" status="500" X-Forwarded-For="fd00:10:17:68:5c85:fb59:2af5:8b9b" Connection="Upgrade" Host="upstream-seacat-auth-8900" Content-Length="36" User-Agent="Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0" Accept="application/json, text/plain, */*" Accept-Language="en-US,en;q=0.5" Accept-Encoding="gzip, deflate, br, zstd" Referer="https://cake1/" Content-Type="application/json" Origin="https://cake1" sec-fetch-dest="empty" sec-fetch-mode="cors" sec-fetch-site="same-origin" priority="u=1" …
```
> Fix attribute error in credentials update

- CHANGELOG.md
- seacatauth/openidconnect/handler/authorize.py
- seacatauth/openidconnect/handler/token.py
- seacatauth/openidconnect/service.py
Token request fails if `anonymous` is in scope.
- Fixed incorrect check on `client["authorize_anonymous_users"]`.
- Fixed broken AlgorithmicSession attributes in token request.
> Fix token request for self-encoded (algorithmic) sessions

- CHANGELOG.md
- seacatauth/cookie/service.py
- seacatauth/openidconnect/service.py
- seacatauth/session/algorithmic.py
When sending an algorithmic session token to nginx oauth introspection, the app logs _"Corrupt access token format: Base64 decoding failed."_ and returns 401.
- Added support for algorithmic tokens to oauth introspection.
- Minor refactoring - use error-driven flow when deserializing algorithmic sessions.
> Accept algorithmic token in oauth introspection

- CHANGELOG.md
- Dockerfile
This is to easily find the used ASAB version in CI/CD build log.
> Print ASAB version during Docker build

- CHANGELOG.md
- seacatauth/session/service.py
Sessions created before https://github.com/TeskaLabs/asab/pull/587 trigger an unhandled ValueError in later versions.
ValueError caught and logged with a warning.
> Handle session decryption error

- CHANGELOG.md
- seacatauth/authz/resource/handler.py
- seacatauth/authz/resource/service.py
- seacatauth/client/handler.py
- seacatauth/client/service.py
- seacatauth/exceptions.py
- Clients and resources with non-empty `managed_by` attribute are considered non-editable.
- Non-editable items are marked with `editable: False` in REST responses.
- Attempts to edit or delete non-editable items raise `seacatauth.exceptions.NotEditableError` which is translated to HTTP response with code 405 and the following body:
```
{
"result": "ERROR",
"tech_err": "Item is not editable."
}
```
> Disable editing of managed items

- CHANGELOG.md
- seacatauth/authz/resource/service.py
- seacatauth/authz/role/handler/role.py
- seacatauth/authz/role/service.py
- seacatauth/authz/role/view/abc.py
- seacatauth/authz/role/view/propagated_role.py
- seacatauth/client/service.py
The `editable` flag is awkward and error-prone to work with, because it is considered `true` by default. `item.get("editable")` is usually just None or False, which both cast to False
Use `read_only` flag which is false by default.
> Replace attribute editable: false with readonly: true

- CHANGELOG.md
- seacatauth/batman/elasticsearch.py
The app does not crash at init when ElasticSearch URL is missing in config. It displays a warning instead.
> Run Batman with warning when there is no ElasticSearch URL

- CHANGELOG.md
- seacatauth/tenant/service.py
When unassigning tenants using `PUT /tenant_assign/{credentials_id}`, there should be no TenantNotFoundError.
> Do not check tenant existence when unassigning tenant

- CHANGELOG.md
- seacatauth/authz/role/handler/role.py
- seacatauth/authz/role/service.py
- Endpoint `POST /role/{tenant}/{role_name}` now has an option to copy resources and description from another role.
- This can be done using a new optional query parameter `copy={role_id}`.
> Duplicating roles

- .github/workflows/ci.yml
- CHANGELOG.md
CICD failing because some github actions have been obsoleted. Example:
https://github.com/TeskaLabs/seacat-auth/actions/runs/10831948469
Upgrade to latest action versions.
> Upgrade CI/CD action versions

- CHANGELOG.md
- seacatauth/credentials/providers/ldap.py
- Proper evaluation of empty string filter in LDAP credentials provider.
- Removed problematic case-sensitive CN comparison: "CN=..." and "cn=..." must be considered the same.
> Fix handling of empty filter in LDAP credentials provider

- CHANGELOG.md
- seacatauth/credentials/providers/ldap.py
When a request to LDAP credentials server fails with `ldap.SERVER_DOWN`, a warning is logged instead of unhandled stacktrace:
```
04-Oct-2024 18:40:10.574199 WARNING seacatauth.credentials.providers.ldap [sd provider_id="ad" uri="ldap://ad.example.int"] LDAP server is down.
```
> Avoid stacktrace when LDAP credentials server is down

- CHANGELOG.md
- example/docker/docker-compose.yml
- seacatauth/provisioning/service.py
When service starts in provisioning mode:
```
12-Nov-2024 11:09:25.732780 ERROR asab.application Error during service initialization
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/asab/application.py", line 730, in _ensure_initialization
await service.initialize(self)
File "/app/seacat-auth/seacatauth/provisioning/service.py", line 101, in initialize
await self.RoleService.create(self.SuperroleID)
File "/app/seacat-auth/seacatauth/authz/role/service.py", line 236, in create
self.validate_superuser_access()
File "/app/seacat-auth/seacatauth/authz/role/service.py", line 298, in validate_superuser_access
raise exceptions.AccessDeniedError(
seacatauth.exceptions.AccessDeniedError: Not authorized to access 'authz:superuser'.
```
Remove duplicate superuser role …
> Fix role error in provisioning startup

- CHANGELOG.md
- seacatauth/tenant/handler.py
The `POST /tenant` endpoint has a new query parameter `assign_me`. When it is set to `yes`, the sender is automatically assigned as the admin of the newly created tenant. If the parameter is false (default), there is no automatic assignment when the tenant is created.
:warning: This changes the behavior of Seacat Admin UI versions lower than `v24.47`. For the best experience, use Seacat Admin UI `v24.47` or later.
> Do not automatically assign tenant to its creator

- CHANGELOG.md
- seacatauth/credentials/providers/ldap.py
Prevent traceback and log an error instead.
> Catch and log ldap.INVALID_CREDENTIALS

- CHANGELOG.md
- seacatauth/openidconnect/handler/token.py
Anonymous sessions are algorithmic - they use self-encoded JWTokens instead of being stored in the database. These tokens have no `exp` attribute, but in the token response there is `expires_in` with default value, which is not true.
Field `expires_in` removed from token response for anonymous sessions.
> Remove expires_in from token response for anonymous sessions

- CHANGELOG.md
- seacatauth/client/service.py
**This is a temporary solution for ASAB Maestro deployments.**
If a public client (`token_endpoint_auth_method: 'none'`) tries to authenticate using a client secret, ignore it instead of denying the request.
> Hotfix: Ignore client secret if client is configured as public

- CHANGELOG.md
- seacatauth/authn/m2m.py
- seacatauth/authn/service.py
- seacatauth/batman/grafana.py
- seacatauth/cookie/service.py
- seacatauth/credentials/service.py
- seacatauth/decorators.py
- seacatauth/models/__init__.py
- seacatauth/models/session.py
- seacatauth/openidconnect/service.py
- seacatauth/provisioning/service.py
- seacatauth/session/__init__.py
- seacatauth/session/algorithmic.py
- seacatauth/session/builders.py
- seacatauth/session/handler.py
- seacatauth/session/service.py
- `SessionAdapter` is renamed to `Session` and moved to `seacatauth.models.session`.
- This is to avoid circular dependencies since SessionAdapter is used everywhere.
> Rename SessionAdapter to Session and move to seacatauth.models

- CHANGELOG.md
- seacatauth/authn/handler.py
- seacatauth/authz/rbac/service.py
- seacatauth/authz/resource/handler.py
- seacatauth/authz/resource/service.py
- seacatauth/authz/role/handler/role.py
- seacatauth/authz/role/handler/roles.py
- seacatauth/authz/role/service.py
- seacatauth/batman/elasticsearch.py
- seacatauth/client/handler.py
- seacatauth/credentials/change_password/handler.py
- seacatauth/credentials/handler.py
- seacatauth/credentials/policy.py
- seacatauth/credentials/registration/handler.py
- seacatauth/decorators.py
- seacatauth/external_login/handler/admin.py
- seacatauth/models/const.py
- seacatauth/models/session.py
- seacatauth/openidconnect/service.py
- seacatauth/session/handler.py
- seacatauth/session/service.py
- seacatauth/tenant/handler.py
- seacatauth/tenant/service.py
All resource IDs are now collected in `seacatauth.models.const.ResourceId` as constants.
> Replace resource ID literals with constants

- CHANGELOG.md
- seacatauth/authz/resource/service.py
- seacatauth/models/const.py
- seacatauth/provisioning/service.py
- seacatauth/tenant/handler.py
- Creating a tenant requires access to `seacat:tenant:create` instead of superuser privileges.
- Fixed provisioning imports.
> Dedicated resource ID for tenant creation

- .github/workflows/ci.yml
- CHANGELOG.md
- seacatauth/client/schema.py
- seacatauth/client/service.py
- seacatauth/cookie/handler.py
- seacatauth/models/const.py
- seacatauth/openidconnect/handler/authorize.py
- seacatauth/openidconnect/handler/discovery.py
- seacatauth/openidconnect/handler/token.py
- seacatauth/openidconnect/pkce.py
- seacatauth/provisioning/service.py
- Replace OAuth2 value strings with constants. They are placed in `seacatauth.models.const.OAuth2`.
- **`BREAKING`** Dropping Python 3.10 support because there is no `StrEnum` in the core library
> Define and use OAuth2 constants

- CHANGELOG.md
- seacatauth/credentials/providers/ldap.py
UNTESTED
```ini
[seacatauth:credentials:ldap:thiscompany]
uri=ldaps://localhost:636
base=OU=Users,OU=Employees,DC=ThisCompany,DC=local
filter=(cn=*)
attrusername=sAMAccountName
tls_cafile=/conf/cert/server-ca.pem
tls_certfile=/conf/cert/local-cert.pem
tls_keyfile=/conf/cert/local-key.pem
```
> Support for tls_certfile and tls_keyfile in LDAP credentials provider

- CHANGELOG.md
- seacatauth/batman/elasticsearch.py
Introducing a new resource `elasticsearch:monitoring` that grants access to Elasticsearch role `monitoring_user` and consequently to Stack Monitoring in Kibana.
Access to this resource must be granted globally (i.e. from a global role) to work. This is because `monitoring_user` has cluster-wide privileges, not restricted to specific spaces.
> Make ES role `monitoring_user` available via resource `elasticsearch:monitoring`

- .github/workflows/ci.yml
- CHANGELOG.md
- Dockerfile
System default Python3.12+ does not allow installing packages because of PEP 668. This replaces the default python with venv python.
> Fix Dockerfile with venv

- CHANGELOG.md
- seacatauth/authz/resource/handler.py
- seacatauth/authz/resource/schema.py
- seacatauth/authz/resource/service.py
- seacatauth/authz/role/handler/role.py
- seacatauth/authz/role/service.py
- seacatauth/batman/elasticsearch.py
- Resources can now be created with attribute `global_only: True`. (Until now this attribute was only transient and was reserved for Seacat Auth system resources.)
- The `global_only` attribute is not editable once the role has been created.
- Global-only resources can only be added to global roles (without propagation) and cannot be added to tenant-scoped roles.
- Marked resources that correspond to cluster level Elasticsearch/Kibana roles as global-only.
- Skip Elasticsearch sync of deleted credentials.
> Make `global_only` a persistent resource attribute

- CHANGELOG.md
- seacatauth/api/tenant.py
- seacatauth/app.py
- seacatauth/authn/webauthn/__init__.py
- seacatauth/authn/webauthn/handler/account.py
- seacatauth/authn/webauthn/handler/admin.py
- seacatauth/authn/webauthn/service.py
- seacatauth/authz/role/service.py
- seacatauth/otp/handler.py
- Introduced admin API for managing TOTP and WebAuthn credentials.
`GET /admin/credentials/{credentials_id}/authn/totp`
Response:
```json
{"active": true|false}
```
`DELETE /admin/credentials/{credentials_id}/authn/totp`
`GET /admin/credentials/{credentials_id}/authn/webauthn`
`GET /admin/credentials/{credentials_id}/authn/webauthn/{passkey_id}`
`PUT /admin/credentials/{credentials_id}/authn/webauthn/{passkey_id}`
`DELETE /admin/credentials/{credentials_id}/authn/webauthn/{passkey_id}`
> TOTP and WebAuthn admin API

- CHANGELOG.md
- seacatauth/credentials/handler.py
Cannot create M2M credentials from the UI.
UI does not send passwordlink with M2M credentials while the backend requires it.
Add default value for passwordlink (False) in credentials creation.
> Add default value for passwordlink in credentials creation

- CHANGELOG.md
- seacatauth/credentials/handler.py
- Credentials API is now prefixed with `/admin`, some paths changed to make the API more RESTful. Old endpoints kept for backward compatibility.
- Added `GET /account/credentials` endpoint.
> Prefix credentials API with /admin
