TeskaLabs/seacat-auth

CHANGELOG.md
Dockerfile

- Dockerfile runs `asab-manifest.py` to generate `MANIFEST.json`.
- App moved to `/app/seacat-auth/`.

Add MANIFEST.json

---

CHANGELOG.md
seacatauth/authz/role/service.py

Role names are validated only at creation time.

Remove regex check for existing roles

---

CHANGELOG.md
seacatauth/__init__.py
seacatauth/cookie/service.py
seacatauth/openidconnect/handler/authorize.py
seacatauth/openidconnect/handler/token.py
seacatauth/openidconnect/service.py

Authorization codes are now stored in a Mongo collection.

Persistent OIDC authorization codes

---

CHANGELOG.md
seacatauth/__init__.py
seacatauth/otp/handler.py
seacatauth/otp/service.py

TOTP secrets are now stored in database
TOTP issuer name now defaults to auth webui hostname.

Persistent TOTP secrets

---

CHANGELOG.md
seacatauth/authn/handler.py
seacatauth/openidconnect/service.py

Change two instances of `datetime.datetime.now` to `datetime.datetime.utcnow`

Use datetime.datetime.utcnow

---

CHANGELOG.md
seacatauth/credentials/handler.py
seacatauth/credentials/service.py
seacatauth/provisioning/service.py
seacatauth/tenant/providers/mongodb.py
seacatauth/tenant/service.py

- Added `delete_credentials` method in `CredentialsService` with necessary pre-deletion cleanups
- Use the new credentials deletion in provisioning

Provisioning cleanup and credentials deletion

---

CHANGELOG.md
seacatauth/session/service.py

Add fallback for backward compatibility

Fix session expiration check

---

CHANGELOG.md
seacatauth/app.py

Temporary fix for until factory methods for WebContainer creation are introduced in TeskaLabs/asab

Temp fix for ASAB WebContainer changes

---

CHANGELOG.md

Credentials: ensure user has at least an email or a phone

Add #41 to Features

---

CHANGELOG.md
seacatauth/credentials/providers/mongodb.py
seacatauth/credentials/service.py

Depends on https://github.com/TeskaLabs/asab/pull/229
Cleaner handling of storage duplicate errors.

Fix for the new asab DuplicateError handling

---

CHANGELOG.md
seacatauth/authz/rbac/handler.py
seacatauth/authz/rbac/service.py
seacatauth/batman/elk.py
seacatauth/batman/grafana.py
seacatauth/credentials/handler.py
seacatauth/exceptions.py
seacatauth/generic.py
seacatauth/middleware.py
seacatauth/tenant/service.py
test/test_rbac.py

- `RBACService.has_resource_access` returns boolean or raises `TenantRequired`
- Introduced exception `TenantRequired`
- **`BREAKING`** Removed obsolete role-checking in Batman.

Make RBAC check return boolean

---

CHANGELOG.md
seacatauth/authn/login_session.py
seacatauth/credentials/service.py
seacatauth/external_login/handler.py

Issue: External login does not work with the new login sessions
Fix: Allow creating login sessions with no client key

Fix external login flow

---

CHANGELOG.md
seacatauth/app.py
seacatauth/credentials/__init__.py
seacatauth/credentials/change_password/__init__.py
seacatauth/credentials/change_password/handler.py
seacatauth/credentials/change_password/service.py
seacatauth/credentials/handler.py

This is to reduce the size of credentials handler.

Move change_password service and handler into credentials submodule

---

CHANGELOG.md
seacatauth/credentials/policy.py

Fix creation policy for M2M provider

Fix M2M provider info

---

CHANGELOG.md
seacatauth/credentials/handler.py

Log a warning when encountering old assignments of deleted credentials in credentials list

Handle old assignments of nonexisting credentials

---

CHANGELOG.md
seacatauth/authz/role/handler/role.py
seacatauth/authz/role/handler/roles.py
seacatauth/authz/role/service.py
seacatauth/tenant/handler.py
seacatauth/tenant/service.py

Fix tenant check when creating/assigning roles

---

CHANGELOG.md
seacatauth/client/handler.py
seacatauth/client/service.py

- Client list now searches both by `_id` and `client_name`
- Removed client values that are not implemented yet

Search clients by name

---

CHANGELOG.md
seacatauth/openidconnect/handler/token.py

`PUT /openidconnect/token/validate` reads JWT ID token from request body or from Bearer token in the Authorization header, checks the validity of the token and responds with token contents or an error.

ID token validation endpoint

---

CHANGELOG.md
doc/seacat-auth-api.postman_collection.json
seacatauth/authz/role/handler/roles.py
seacatauth/tenant/handler.py

- endpoint `PUT /tenants`
- takes a json array of credential ids
Request
```json
PUT /tenants
[
"mongodb:ext:60dd746205487b6bcfb03e92",
"mongodb:ext:60eee70d6b47935cf7bacdda"
]
```
Response
```json
{
"mongodb:ext:60dd746205487b6bcfb03e92": [
"best-tenant",
"default",
"druhej",
"jeden"
],
"mongodb:ext:60eee70d6b47935cf7bacdda": [
"another-tenant",
"default"
]
}
```
- endpoint `PUT /roles/{tenant}`
- takes a json array of credential ids
Request
```json
PUT /roles/default
[
"mongodb:ext:60dd746205487b6bcfb03e92",
"mongodb:ext:60eee70d6b47935cf7bacdda"
]
```
Response
```json
{
"mongodb:ext:60dd746205487b6bcfb03e92": [
"*/superuser",
"default/admin",
"*/seacat-user"
],
"mongodb:ext:60eee70d6b47935cf7bacdda": [
"*/seacat-user",
"default/admin"
]
}
```

List tenants and roles for multiple credentials

---

CHANGELOG.md
seacatauth/authz/role/handler/role.py
seacatauth/authz/role/service.py
seacatauth/provisioning/service.py
seacatauth/tenant/service.py

Roles now contain optional editable `description` field.
Update using 
```json
PUT /role/<role_id>
{
"description": <description_string>
}
```

Role description field

---

CHANGELOG.md
seacatauth/decorators.py

Do not check if tenant exists when the tenant is None

---

etc/message_templates/email/cs-invitation.html
etc/message_templates/email/cs-self_registration.html
etc/message_templates/email/en-invitation.html
etc/message_templates/email/en-self_registration.html
seacatauth/communication/service.py
seacatauth/credentials/registration/handler.py

- Invitation mail now lists all the tenants where the user is invited.
- Invitation mail now includes expiration datetime.

Refactoring of registration mail templates

---

CHANGELOG.md
seacatauth/client/handler.py
seacatauth/client/service.py

- added regex for `cookie_domain`
- removed the requirement for redirect_uri and client_name in the update call

Client metadata refactoring

---

CHANGELOG.md
seacatauth/client/handler.py
seacatauth/client/service.py

Send empty string `""` or `null` as a value in `PUT /client/<client_id>` to unset the respective feature.

Unset client features

---

CHANGELOG.md
seacatauth/credentials/providers/abc.py
seacatauth/credentials/providers/mongodb.py
seacatauth/credentials/providers/xmongodb.py

Improve MongoDB credential count performance

---

CHANGELOG.md
seacatauth/cookie/handler.py
seacatauth/openidconnect/session.py

"Trampoline" doesn't work because of these two little bugs.

Fix cookie client session flow

---

CHANGELOG.md
Dockerfile
doc/docker/docker-compose.yml
doc/docker/nginx-conf/nginx.conf
seacatauth/credentials/service.py

- Fix credential service lookup to match new asab version
- Update example site config

Fix credential service lookup

---

CHANGELOG.md
seacatauth/client/service.py
seacatauth/credentials/service.py
seacatauth/provisioning/service.py

- Fixed ASAB webui client provisioning.
- Provisioning service awaits Client service initialization.
- Fixed role unassignment in provisioning finalization.

Fix provisioning flow

---

CHANGELOG.md
seacatauth/provisioning/service.py

Fix provisioning initialization conflicts

Make provisioning initialization defensive against database state

---

CHANGELOG.md
seacatauth/app.py

Explicitly initialize metrics (metrics endpoints are no longer initialized automatically with the ASAB web service).

Reintroduce metrics

---

.github/workflows/ci.yml
CHANGELOG.md
Dockerfile

also docker Alpine version is upgraded to 3.18

Bump python version to 3.11

---

CHANGELOG.md
Dockerfile

Provides a hotfix for this issue:
https://github.com/duo-labs/py_webauthn/issues/156

Hotfix broken webauthn dependency

---

CHANGELOG.md
seacatauth/cookie/service.py
seacatauth/openidconnect/handler/authorize.py
seacatauth/openidconnect/service.py
seacatauth/openidconnect/session.py
seacatauth/session/adapter.py

Implement authorize parameter `nonce`

---

CHANGELOG.md
seacatauth/app.py

Initializes `asab.ZookeeperService` when `zookeeper` section is in config. It is not there by default.

Initialize Zookeeper

---

CHANGELOG.md
Dockerfile
seacatauth/app.py

Enables sentry service when `sentry` section is in the config.

Add Sentry service

---

CHANGELOG.md
seacatauth/app.py

self.App.Provisioning doesn't exist anymore - use self.Provisioning

Fix private key provisioning

---

CHANGELOG.md
seacatauth/credentials/change_password/handler.py
seacatauth/credentials/change_password/service.py
seacatauth/exceptions.py
seacatauth/external_login/handler.py

- Log failed password change requests
- Inform about failure in Admin API
- Do not disclose the failure in Public API

Log failed password change requests

---

CHANGELOG.md
seacatauth/external_login/providers/github.py

- Get Github user's email via [user emails API](https://docs.github.com/en/rest/users/emails?apiVersion=2022-11-28#list-email-addresses-for-the-authenticated-user).

Github user email

---

CHANGELOG.md
seacatauth/authn/m2m.py
seacatauth/cookie/handler.py
seacatauth/cookie/service.py
seacatauth/openidconnect/handler/introspect.py

Log reasons for introspection failure.

Introspection logging

---

CHANGELOG.md
seacatauth/app.py
seacatauth/batman/grafana.py
seacatauth/external_login/providers/generic.py
seacatauth/openidconnect/handler/introspect.py
seacatauth/session/service.py

Frequent NOTICE-level messages reduced to INFO.

Silence stable log messages

---

CHANGELOG.md
seacatauth/client/service.py
seacatauth/cookie/handler.py

- Fixed cookie introspection
- Lower client ID length limit (4 characters)

Fix client cookie introspection

---

CHANGELOG.md
seacatauth/cookie/handler.py
seacatauth/openidconnect/handler/authorize.py
seacatauth/openidconnect/handler/token.py

Added log entries for
- successful authorization message
- successful token request message
- successful cookie request message

Log successful authorization requests

---

CHANGELOG.md
seacatauth/authz/resource/handler.py
seacatauth/authz/resource/service.py

Fixes the initialization and updating of built-in resources.

Fix resource initialization

---

CHANGELOG.md
seacatauth/authz/resource/handler.py
seacatauth/authz/resource/service.py

- Searching in resources matches anywhere in resource name (used to match only at the beginning).
- Resource list is sorted alphabetically (used to be sorted by creation time).

Improve resource filtering and sort them alphabetically

---

.github/workflows/ci.yml
CHANGELOG.md
Dockerfile
seacatauth/authz/resource/handler.py
seacatauth/authz/resource/service.py
seacatauth/authz/role/service.py
seacatauth/client/service.py
seacatauth/communication/sms_smsbranacz.py
seacatauth/credentials/change_password/handler.py
seacatauth/credentials/providers/abc.py
seacatauth/credentials/providers/dictionary.py
seacatauth/credentials/providers/htpasswd.py
seacatauth/credentials/providers/m2m_mongodb.py
seacatauth/credentials/providers/mongodb.py
seacatauth/credentials/providers/mysql.py
seacatauth/credentials/providers/xmongodb.py
seacatauth/credentials/service.py
seacatauth/decorators.py
seacatauth/exceptions.py
seacatauth/generic.py
seacatauth/openidconnect/handler/authorize.py
seacatauth/openidconnect/service.py
seacatauth/provisioning/service.py
seacatauth/tenant/providers/mongodb.py
seacatauth/tenant/service.py

* Deny password change when old password verification fails by @byewokko in https://github.com/TeskaLabs/seacat-auth/pull/374
* User invitations are enabled by default by @byewokko in https://github.com/TeskaLabs/seacat-auth/pull/367
* Improve resource filtering and sort them alphabetically by @byewokko in https://github.com/TeskaLabs/seacat-auth/pull/370
* Deprecate passlib by @byewokko in https://github.com/TeskaLabs/seacat-auth/pull/368
* Consistent use of item-specific not-found exceptions by @byewokko in https://github.com/TeskaLabs/seacat-auth/pull/371
* Authorize into last active tenant by @byewokko in https://github.com/TeskaLabs/seacat-auth/pull/373
**Full Changelog**: https://github.com/TeskaLabs/seacat-auth/compare/v24.17-beta1...v24.17-beta2

Advance branch to v24.17-beta2

---

seacatauth/generic.py

Handle Argon2 VerifyMismatchError

---

CHANGELOG.md
seacatauth/authn/service.py
seacatauth/session/service.py

Move SSO session creation into session service and refactor for reusability.

Move SSO session creation into session service

---

CHANGELOG.md
seacatauth/client/service.py

Client ID is not always known in advance, so it should be optional.

Expected client ID is optional for authentication

---

CHANGELOG.md
seacatauth/credentials/service.py

Patch v24.17: Fix attribute error in credentials update

---

CHANGELOG.md
seacatauth/authn/login_descriptor.py

```
26-Jun-2024 17:02:57.286865 NOTICE seacatauth.authn.login_descriptor [sd descriptor_id="default" factor_type="password" cid="mongodb:ext:624c3d25a2fa80a0f42ba503"] Login factor verification failed.
```

Log login factor verification failure

---

CHANGELOG.md
seacatauth/client/handler.py
seacatauth/client/service.py
seacatauth/generic.py

- Client list is sorted alphabetically by client name (case-insensitive).
- Client list supports sorting by standard DataTable2 query params.

Sort clients alphabetically by client name

---

CHANGELOG.md
seacatauth/authz/role/service.py
seacatauth/tenant/handler.py
seacatauth/tenant/providers/mongodb.py
seacatauth/tenant/service.py

User tenants and roles are now sorted alphabetically if possible.

Sort assigned tenants and roles alphabetically

---

CHANGELOG.md
seacatauth/credentials/providers/ldap.py

- Improve default settings: 
- Include userAccountControl to derive `suspended` info.
- Include displayName in results.
- Set username attr to sAMAccountName.
- Remove code duplication, improve legibility.

LDAP credentials provider refactoring

---

.github/workflows/ci.yml
CHANGELOG.md

`v24.29` did not build because of obsolete cicd actions
see #418 for details

Upgrade CI/CD action versions

---

CHANGELOG.md
seacatauth/credentials/schemas.py

Fix validation schema for credentials custom `data` field.

Fix credentials custom data editing

---

CHANGELOG.md
seacatauth/authz/utils.py
seacatauth/credentials/providers/mongodb.py
seacatauth/credentials/service.py
seacatauth/tenant/providers/abc.py
seacatauth/tenant/providers/mongodb.py
seacatauth/tenant/service.py

Always initialize tenant provider by default. (Tenant service with a functioning provider is required by the app anyways.)

Always initialize tenant provider

---

CHANGELOG.md
etc/message_templates/email/cs-invitation.html
etc/message_templates/email/cs-password_reset.html
etc/message_templates/email/cs-password_reset_welcome.html
etc/message_templates/email/cs-self_registration.html
etc/message_templates/email/en-invitation.html
etc/message_templates/email/en-password_reset.html
etc/message_templates/email/en-password_reset_welcome.html
etc/message_templates/email/en-self_registration.html
etc/message_templates/sms/cs-password_reset.txt
etc/message_templates/sms/cs-password_reset_welcome.txt
etc/message_templates/sms/en-password_reset.txt
etc/message_templates/sms/en-password_reset_welcome.txt
seacatauth/communication/service.py

Rename email template parameters

---

CHANGELOG.md
seacatauth/credentials/registration/service.py

Added missing local authz context in processing invitations as existing user.

Fix authorization in accepting an invitation as an existing user

---

CHANGELOG.md
seacatauth/credentials/providers/abc.py
seacatauth/credentials/providers/dictionary.py
seacatauth/credentials/providers/elasticsearch.py
seacatauth/credentials/providers/htpasswd.py
seacatauth/credentials/providers/ldap.py
seacatauth/credentials/providers/m2m_mongodb.py
seacatauth/credentials/providers/mongodb.py
seacatauth/credentials/providers/mysql.py
seacatauth/credentials/providers/xmongodb.py

- Common method for converting credentials ID to inner database ID.
- Credentials providers have reference to application object.

Common method for converting credentials ID to inner database ID

---

CHANGELOG.md
seacatauth/client/schema.py
seacatauth/client/service.py
seacatauth/credentials/providers/client.py

Virtual Seacat Auth credentials are created only for clients with `seacatauth_credentials` attribute `True`.

Only clients with `seacatauth_credentials: True` have credentials API

---

seacatauth/credentials/providers/ldap.py

LDAP client cert support

---

CHANGELOG.md
seacatauth/credentials/providers/client.py

Naming bug in client credentials provider broke all credentials searching.
Fix typo.

Fix credentials search

---

CHANGELOG.md
seacatauth/credentials/handler.py

- Add default value for passwordlink in credentials creation (#494, v25.26-alpha2)

Patch v25.13 beta2: Fix m2m cred creation

---

CHANGELOG.md
seacatauth/credentials/handler.py

Use the a- prefix to ensure compatibility with the DataTable webui component.

Rename credentials "status" param to "astatus"
